epos2_arm_controller:
  ros__parameters:
    joint_names: ["joint3"]
    clear_fault_services: ["/epos2/j3/clear_fault"]
    arm_services: ["/epos2/j3/arm_ipm"]
    disarm_services: ["/epos2/j3/disarm_ipm"]
    move_services: ["/epos2/j3/move_absolute_timed"]
    goal_position_tolerance_rad: 0.03
    wait_for_joint_state_sec: 5.0
